from django.urls import path
from .views import *

urlpatterns = {
    path('login', login),
    path('register', register),
    path('create_team', create_team),
    path('authorize_admin', authorize_admin),
    path('invite_user', invite_user),
    path('delete_member', delete_member),
    path('userspace', userspace),
    path('teamspace', teamspace),
    path('team_manage', team_manage),
    path('modify_username', modify_username),
    path('modify_password', modify_password),
    path('modify_photo', modify_photo),
    path('delete_team', delete_team),
    path('handleInvitation', handleInvitation),
    path('search_team', search_team),
    path('apply_join', apply_join),
    path('search_user', search_user),
    path('sendVerifyCode', sendVerifyCode),
    path('acceptInvitation', acceptInvitation),
    path('createFolder', createFolder),
    path('renameFolder', renameFolder),
    path('deleteFolder', deleteFolder),
    path('moveFolder', moveFolder),
    path('moveFile', moveFile),
    path('copyTeamFile', copyTeamFile),
    path('file_center', file_center),
}
