# Generated by Django 4.0.4 on 2022-08-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteMessage',
            fields=[
                ('inviteId', models.AutoField(primary_key=True, serialize=False)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter_message', to='team.user')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to='team.user')),
            ],
        ),
    ]
