# Generated by Django 4.0.4 on 2022-08-09 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_invitemessage_readstatus_invitemessage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemessage',
            name='deleteTeamName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invitemessage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
