from django.urls import path
from .views import *

urlpatterns = {
    path('createProj', createProj),
    path('modifyProjPhoto', modifyProjPhoto),
    path('modifyProjInfo', modifyProjInfo),
    path('deleteProj', deleteProj),
    path('clearProj', clearProj),
    path('getDeletedProjList', getDeletedProjList),
    path('recover', recoverProj),
    path('detail', detailProj),
    path('copy_project', copy_project),
    path('create_proto', create_proto),
    path('upload_proto', upload_proto),
    path('upload_proto_photo', upload_proto_photo),
    path('get_proto', get_proto),
    path('rename_proto', rename_proto),
    path('delete_proto', delete_proto),
    path('proj_proto', proj_proto),
    path('createFile', createFile),
    path('deleteFile', deleteFile),
    path('modifyFile', modifyFile),
    path('renameFile', renameFile),
    path('getFileList', getFileList),
    path('getFileContent', getFileContent),
    path('edit_file', edit_file),
    path('upload_file_image', upload_file_image),
    path('search_team_project', search_team_project),
    path('search_user_project', search_user_project),
    path('project_order', project_order),
    path('get_pdf', get_pdf),
    path('delete_pdf', delete_pdf),
    path('open_proto_preview', open_proto_preview),
    path('close_proto_preview', close_proto_preview),
    path('view_proto_preview', view_proto_preview),
    path('view_preview_status', view_preview_status),
    path('copy_project_file', copy_project_file),
}
