# Generated by Django 4.0.4 on 2022-08-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projId', models.AutoField(primary_key=True, serialize=False)),
                ('projName', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('deleteTime', models.CharField(blank=True, max_length=20, null=True)),
                ('deletePerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletePerson', to='team.user')),
                ('projCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='team.user')),
                ('projTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('prototypeId', models.AutoField(primary_key=True, serialize=False)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=50, unique=True)),
                ('fileCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.user')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
