# Generated by Django 3.2.5 on 2022-08-03 05:57

from django.db import migrations, models
import django.db.models.deletion
import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projId', models.AutoField(primary_key=True, serialize=False)),
                ('projName', models.CharField(max_length=50, unique=True)),
                ('projInfo', models.TextField(default='暂无简介')),
                ('startTime', models.CharField(blank=True, max_length=20, null=True)),
                ('endTime', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(default=1)),
                ('deleteTime', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(default='projImg/default.png', storage=utils.storage.ImageStorage(), upload_to='projImg')),
                ('deletePerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletePerson', to='team.user')),
                ('projCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='team.user')),
                ('projTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('prototypeId', models.AutoField(primary_key=True, serialize=False)),
                ('protoName', models.CharField(default='proto_default', max_length=50, unique=True)),
                ('protoFile', models.FileField(default='projProto/proto_default.json', storage=utils.storage.ProtoStorage, upload_to='projProto')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('protoCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('create', models.CharField(blank=True, max_length=25, null=True)),
                ('lastEditTime', models.CharField(blank=True, max_length=20, null=True)),
                ('fileCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileCreator', to='team.user')),
                ('lastEditUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastEditUser', to='team.user')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
