# Generated by Django 4.0.4 on 2022-08-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='endTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projInfo',
            field=models.TextField(default='暂无简介'),
        ),
        migrations.AddField(
            model_name='project',
            name='startTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
