# Generated by Django 4.0.4 on 2022-08-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_endtime_project_projinfo_project_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='projImg/default.png', upload_to='projImg'),
        ),
    ]
