# Generated by Django 4.0.4 on 2022-08-02 09:52

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='projImg/default.png', storage=utils.storage.ImageStorage(), upload_to='projImg'),
        ),
    ]
