# Generated by Django 4.0.4 on 2022-08-03 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_user_photo'),
        ('project', '0004_alter_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='create',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='lastEditTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='lastEditUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastEditUser', to='team.user'),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileCreator', to='team.user'),
        ),
    ]
