# Generated by Django 4.0.4 on 2022-08-03 06:02

from django.db import migrations, models
import django.db.models.deletion
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_user_photo'),
        ('project', '0005_file_content_file_create_file_lastedittime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='protoCreator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.user'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='protoFile',
            field=models.FileField(default='projProto/proto_default.json', storage=utils.storage.ProtoStorage, upload_to='projProto'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='protoName',
            field=models.CharField(default='proto_default', max_length=50, unique=True),
        ),
    ]
