# Generated by Django 4.0.4 on 2022-08-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_prototype_protocreator_prototype_protofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lastEditTimeRecord',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
