# Generated by Django 4.0.4 on 2022-08-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_file_lastedittimerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleteTimeRecord',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
