# Generated by Django 3.2.5 on 2022-08-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_file_lastedittimerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototype',
            name='protoFile',
        ),
        migrations.AddField(
            model_name='prototype',
            name='protoContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
