# Generated by Django 4.0.4 on 2022-08-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_deletetimerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deleteTimeRecord',
            field=models.DateTimeField(),
        ),
    ]
