# Generated by Django 3.2.5 on 2022-08-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20220804_0918'),
        ('project', '0010_alter_project_deletetimerecord'),
    ]

    operations = [
    ]
