# Generated by Django 3.2.5 on 2022-08-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_merge_20220804_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='protoPhoto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
