# Generated by Django 3.2.5 on 2022-08-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_prototype_protophoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='protoContent',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
