# Generated by Django 4.0.4 on 2022-08-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_prototype_protocontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileName',
            field=models.CharField(max_length=50),
        ),
    ]
