# Generated by Django 4.0.4 on 2022-08-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_file_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projName',
            field=models.CharField(max_length=50),
        ),
    ]
