# Generated by Django 3.2.5 on 2022-08-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_invitemessage'),
        ('project', '0016_prototype_canvas_height_prototype_canvas_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.user')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='edit_file',
            field=models.ManyToManyField(through='project.UserFile', to='team.User'),
        ),
    ]
