# Generated by Django 3.2.5 on 2022-08-06 04:34

from django.db import migrations, models
import django.db.models.deletion
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20220805_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=utils.storage.ImageStorage, upload_to='fileImg')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.file')),
            ],
        ),
    ]
