# Generated by Django 3.2.5 on 2022-08-07 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_invitemessage_readstatus_invitemessage_status_and_more'),
        ('project', '0018_fileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileTeam', to='team.team'),
        ),
        migrations.AddField(
            model_name='file',
            name='judge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='new',
            field=models.IntegerField(default=1),
        ),
    ]
