# Generated by Django 3.2.5 on 2022-08-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_project_copy_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='file_model',
            field=models.IntegerField(default=0),
        ),
    ]
