# Generated by Django 4.0.4 on 2022-08-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_project_preview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='protoName',
            field=models.CharField(default='proto_default', max_length=50),
        ),
    ]
